<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-3BL6A4A" failures="1" tests="1" name="extent Report Tests" time="31.407" errors="0" timestamp="2024-02-17T00:09:48 EET">
  <testcase classname="smokeTest.Checkout" name="checkoutTest" time="31.153">
    <failure type="java.lang.AssertionError" message="expected [1Thank you for your purchase!] but found [Thank you for your purchase!]">
      <![CDATA[java.lang.AssertionError: expected [1Thank you for your purchase!] but found [Thank you for your purchase!]
at pageObjects.Assertions.checkThatCheckoutSuccess(Assertions.java:10)
at smokeTest.Checkout.checkoutTest(Checkout.java:63)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- checkoutTest -->
</testsuite> <!-- extent Report Tests -->
